// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./test.proto

// protoc -I ./ --go_out=. ./test/test.proto
// protoc -I ./ --go-grpc_out=. test/test.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: test/test.proto

package test

import (
	context "context"
	api "github.com/air-iot/api-client-go/v4/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FlowTaskService_Get_FullMethodName = "/test.FlowTaskService/Get"
)

// FlowTaskServiceClient is the client API for FlowTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowTaskServiceClient interface {
	Get(ctx context.Context, in *api.GetOrDeleteRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type flowTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowTaskServiceClient(cc grpc.ClientConnInterface) FlowTaskServiceClient {
	return &flowTaskServiceClient{cc}
}

func (c *flowTaskServiceClient) Get(ctx context.Context, in *api.GetOrDeleteRequest, opts ...grpc.CallOption) (*api.Response, error) {
	out := new(api.Response)
	err := c.cc.Invoke(ctx, FlowTaskService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowTaskServiceServer is the server API for FlowTaskService service.
// All implementations must embed UnimplementedFlowTaskServiceServer
// for forward compatibility
type FlowTaskServiceServer interface {
	Get(context.Context, *api.GetOrDeleteRequest) (*api.Response, error)
	mustEmbedUnimplementedFlowTaskServiceServer()
}

// UnimplementedFlowTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlowTaskServiceServer struct {
}

func (UnimplementedFlowTaskServiceServer) Get(context.Context, *api.GetOrDeleteRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFlowTaskServiceServer) mustEmbedUnimplementedFlowTaskServiceServer() {}

// UnsafeFlowTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowTaskServiceServer will
// result in compilation errors.
type UnsafeFlowTaskServiceServer interface {
	mustEmbedUnimplementedFlowTaskServiceServer()
}

func RegisterFlowTaskServiceServer(s grpc.ServiceRegistrar, srv FlowTaskServiceServer) {
	s.RegisterService(&FlowTaskService_ServiceDesc, srv)
}

func _FlowTaskService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GetOrDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowTaskServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowTaskService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowTaskServiceServer).Get(ctx, req.(*api.GetOrDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowTaskService_ServiceDesc is the grpc.ServiceDesc for FlowTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.FlowTaskService",
	HandlerType: (*FlowTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _FlowTaskService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/test.proto",
}
