// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./live/live.proto

// protoc -I ./ --go_out=. ./live/live.proto
// protoc -I ./ --go-grpc_out=. live/live.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: live/live.proto

package live

import (
	api "github.com/air-iot/api-client-go/v4/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveStopStreamByStreamPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=streamPath,proto3" json:"streamPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveStopStreamByStreamPathRequest) Reset() {
	*x = LiveStopStreamByStreamPathRequest{}
	mi := &file_live_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveStopStreamByStreamPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStopStreamByStreamPathRequest) ProtoMessage() {}

func (x *LiveStopStreamByStreamPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStopStreamByStreamPathRequest.ProtoReflect.Descriptor instead.
func (*LiveStopStreamByStreamPathRequest) Descriptor() ([]byte, []int) {
	return file_live_live_proto_rawDescGZIP(), []int{0}
}

func (x *LiveStopStreamByStreamPathRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

var File_live_live_proto protoreflect.FileDescriptor

const file_live_live_proto_rawDesc = "" +
	"\n" +
	"\x0flive/live.proto\x12\x04live\x1a\rapi/api.proto\"C\n" +
	"!LiveStopStreamByStreamPathRequest\x12\x1e\n" +
	"\n" +
	"streamPath\x18\x01 \x01(\tR\n" +
	"streamPath2\xc8\x01\n" +
	"\vLiveService\x126\n" +
	"\x10QueryStreamsInfo\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12R\n" +
	"\x16StopStreamByStreamPath\x12'.live.LiveStopStreamByStreamPathRequest\x1a\r.api.Response\"\x00B;\n" +
	"$cn.airiot.sdk.client.dubbo.grpc.liveP\x01Z\v./live;live\x88\x01\x01\xa0\x01\x01b\x06proto3"

var (
	file_live_live_proto_rawDescOnce sync.Once
	file_live_live_proto_rawDescData []byte
)

func file_live_live_proto_rawDescGZIP() []byte {
	file_live_live_proto_rawDescOnce.Do(func() {
		file_live_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_live_live_proto_rawDesc), len(file_live_live_proto_rawDesc)))
	})
	return file_live_live_proto_rawDescData
}

var file_live_live_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_live_live_proto_goTypes = []any{
	(*LiveStopStreamByStreamPathRequest)(nil), // 0: live.LiveStopStreamByStreamPathRequest
	(*api.QueryRequest)(nil),                  // 1: api.QueryRequest
	(*api.CreateRequest)(nil),                 // 2: api.CreateRequest
	(*api.Response)(nil),                      // 3: api.Response
}
var file_live_live_proto_depIdxs = []int32{
	1, // 0: live.LiveService.QueryStreamsInfo:input_type -> api.QueryRequest
	2, // 1: live.LiveService.Create:input_type -> api.CreateRequest
	0, // 2: live.LiveService.StopStreamByStreamPath:input_type -> live.LiveStopStreamByStreamPathRequest
	3, // 3: live.LiveService.QueryStreamsInfo:output_type -> api.Response
	3, // 4: live.LiveService.Create:output_type -> api.Response
	3, // 5: live.LiveService.StopStreamByStreamPath:output_type -> api.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_live_live_proto_init() }
func file_live_live_proto_init() {
	if File_live_live_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_live_live_proto_rawDesc), len(file_live_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_live_live_proto_goTypes,
		DependencyIndexes: file_live_live_proto_depIdxs,
		MessageInfos:      file_live_live_proto_msgTypes,
	}.Build()
	File_live_live_proto = out.File
	file_live_live_proto_goTypes = nil
	file_live_live_proto_depIdxs = nil
}
