// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: engine/engine.proto

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/engine.EngineService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/engine.EngineService/Resume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/engine.EngineService/Fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility
type EngineServiceServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Resume(context.Context, *ResumeRequest) (*emptypb.Empty, error)
	Fail(context.Context, *FailRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEngineServiceServer struct {
}

func (UnimplementedEngineServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedEngineServiceServer) Resume(context.Context, *ResumeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedEngineServiceServer) Fail(context.Context, *FailRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.EngineService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.EngineService/Resume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.EngineService/Fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _EngineService_Run_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _EngineService_Resume_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _EngineService_Fail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine/engine.proto",
}

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Register(ctx context.Context, opts ...grpc.CallOption) (PluginService_RegisterClient, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/engine.PluginService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Register(ctx context.Context, opts ...grpc.CallOption) (PluginService_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], "/engine.PluginService/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginServiceRegisterClient{stream}
	return x, nil
}

type PluginService_RegisterClient interface {
	Send(*FlowResponse) error
	Recv() (*FlowRequest, error)
	grpc.ClientStream
}

type pluginServiceRegisterClient struct {
	grpc.ClientStream
}

func (x *pluginServiceRegisterClient) Send(m *FlowResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pluginServiceRegisterClient) Recv() (*FlowRequest, error) {
	m := new(FlowRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Register(PluginService_RegisterServer) error
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginServiceServer) Register(PluginService_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.PluginService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServiceServer).Register(&pluginServiceRegisterServer{stream})
}

type PluginService_RegisterServer interface {
	Send(*FlowRequest) error
	Recv() (*FlowResponse, error)
	grpc.ServerStream
}

type pluginServiceRegisterServer struct {
	grpc.ServerStream
}

func (x *pluginServiceRegisterServer) Send(m *FlowRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pluginServiceRegisterServer) Recv() (*FlowResponse, error) {
	m := new(FlowResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PluginService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _PluginService_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine/engine.proto",
}

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionServiceClient interface {
	HealthCheck(ctx context.Context, in *ExtensionHealthCheckRequest, opts ...grpc.CallOption) (*ExtensionHealthCheckResponse, error)
	SchemaStream(ctx context.Context, opts ...grpc.CallOption) (ExtensionService_SchemaStreamClient, error)
	RunStream(ctx context.Context, opts ...grpc.CallOption) (ExtensionService_RunStreamClient, error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) HealthCheck(ctx context.Context, in *ExtensionHealthCheckRequest, opts ...grpc.CallOption) (*ExtensionHealthCheckResponse, error) {
	out := new(ExtensionHealthCheckResponse)
	err := c.cc.Invoke(ctx, "/engine.ExtensionService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) SchemaStream(ctx context.Context, opts ...grpc.CallOption) (ExtensionService_SchemaStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExtensionService_ServiceDesc.Streams[0], "/engine.ExtensionService/SchemaStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &extensionServiceSchemaStreamClient{stream}
	return x, nil
}

type ExtensionService_SchemaStreamClient interface {
	Send(*ExtensionResult) error
	Recv() (*ExtensionSchemaRequest, error)
	grpc.ClientStream
}

type extensionServiceSchemaStreamClient struct {
	grpc.ClientStream
}

func (x *extensionServiceSchemaStreamClient) Send(m *ExtensionResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *extensionServiceSchemaStreamClient) Recv() (*ExtensionSchemaRequest, error) {
	m := new(ExtensionSchemaRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *extensionServiceClient) RunStream(ctx context.Context, opts ...grpc.CallOption) (ExtensionService_RunStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExtensionService_ServiceDesc.Streams[1], "/engine.ExtensionService/RunStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &extensionServiceRunStreamClient{stream}
	return x, nil
}

type ExtensionService_RunStreamClient interface {
	Send(*ExtensionResult) error
	Recv() (*ExtensionRunRequest, error)
	grpc.ClientStream
}

type extensionServiceRunStreamClient struct {
	grpc.ClientStream
}

func (x *extensionServiceRunStreamClient) Send(m *ExtensionResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *extensionServiceRunStreamClient) Recv() (*ExtensionRunRequest, error) {
	m := new(ExtensionRunRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility
type ExtensionServiceServer interface {
	HealthCheck(context.Context, *ExtensionHealthCheckRequest) (*ExtensionHealthCheckResponse, error)
	SchemaStream(ExtensionService_SchemaStreamServer) error
	RunStream(ExtensionService_RunStreamServer) error
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExtensionServiceServer struct {
}

func (UnimplementedExtensionServiceServer) HealthCheck(context.Context, *ExtensionHealthCheckRequest) (*ExtensionHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedExtensionServiceServer) SchemaStream(ExtensionService_SchemaStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SchemaStream not implemented")
}
func (UnimplementedExtensionServiceServer) RunStream(ExtensionService_RunStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method RunStream not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtensionHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ExtensionService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).HealthCheck(ctx, req.(*ExtensionHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_SchemaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExtensionServiceServer).SchemaStream(&extensionServiceSchemaStreamServer{stream})
}

type ExtensionService_SchemaStreamServer interface {
	Send(*ExtensionSchemaRequest) error
	Recv() (*ExtensionResult, error)
	grpc.ServerStream
}

type extensionServiceSchemaStreamServer struct {
	grpc.ServerStream
}

func (x *extensionServiceSchemaStreamServer) Send(m *ExtensionSchemaRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *extensionServiceSchemaStreamServer) Recv() (*ExtensionResult, error) {
	m := new(ExtensionResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ExtensionService_RunStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExtensionServiceServer).RunStream(&extensionServiceRunStreamServer{stream})
}

type ExtensionService_RunStreamServer interface {
	Send(*ExtensionRunRequest) error
	Recv() (*ExtensionResult, error)
	grpc.ServerStream
}

type extensionServiceRunStreamServer struct {
	grpc.ServerStream
}

func (x *extensionServiceRunStreamServer) Send(m *ExtensionRunRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *extensionServiceRunStreamServer) Recv() (*ExtensionResult, error) {
	m := new(ExtensionResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ExtensionService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SchemaStream",
			Handler:       _ExtensionService_SchemaStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RunStream",
			Handler:       _ExtensionService_RunStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine/engine.proto",
}
