// Copyright 2015 The gRPC Authors
// protoc -I . --go_out=plugins=grpc:. ./core.proto   不用

// protoc -I ./ --go_out=. ./core/core.proto
// protoc -I ./ --go-grpc_out=. core/core.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: core/core.proto

package core

import (
	api "github.com/air-iot/api-client-go/v4/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_core_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetDeviceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetDataDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataDeviceRequest) Reset() {
	*x = GetDataDeviceRequest{}
	mi := &file_core_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataDeviceRequest) ProtoMessage() {}

func (x *GetDataDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDataDeviceRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataDeviceRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetDataDeviceRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetDataDeviceRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetDataDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequestName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestName) Reset() {
	*x = GetRequestName{}
	mi := &file_core_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestName) ProtoMessage() {}

func (x *GetRequestName) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestName.ProtoReflect.Descriptor instead.
func (*GetRequestName) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Query         []byte                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDataRequest) Reset() {
	*x = QueryDataRequest{}
	mi := &file_core_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataRequest) ProtoMessage() {}

func (x *QueryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataRequest.ProtoReflect.Descriptor instead.
func (*QueryDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{3}
}

func (x *QueryDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *QueryDataRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetOrDeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrDeleteDataRequest) Reset() {
	*x = GetOrDeleteDataRequest{}
	mi := &file_core_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrDeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrDeleteDataRequest) ProtoMessage() {}

func (x *GetOrDeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrDeleteDataRequest.ProtoReflect.Descriptor instead.
func (*GetOrDeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrDeleteDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetOrDeleteDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,4,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_core_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type MultiUpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Query         []byte                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,4,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiUpdateDataRequest) Reset() {
	*x = MultiUpdateDataRequest{}
	mi := &file_core_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiUpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiUpdateDataRequest) ProtoMessage() {}

func (x *MultiUpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiUpdateDataRequest.ProtoReflect.Descriptor instead.
func (*MultiUpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{6}
}

func (x *MultiUpdateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *MultiUpdateDataRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *MultiUpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MultiUpdateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type CreateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CloseRequire  bool                   `protobuf:"varint,3,opt,name=closeRequire,proto3" json:"closeRequire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataRequest) Reset() {
	*x = CreateDataRequest{}
	mi := &file_core_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataRequest) ProtoMessage() {}

func (x *CreateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataRequest.ProtoReflect.Descriptor instead.
func (*CreateDataRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDataRequest) GetCloseRequire() bool {
	if x != nil {
		return x.CloseRequire
	}
	return false
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_core_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{8}
}

func (x *LoginUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_core_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{9}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_core_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MediaLibraryQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	AddBase64     bool                   `protobuf:"varint,2,opt,name=addBase64,proto3" json:"addBase64,omitempty"`
	IsFile        bool                   `protobuf:"varint,3,opt,name=isFile,proto3" json:"isFile,omitempty"`
	Query         []byte                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryQueryRequest) Reset() {
	*x = MediaLibraryQueryRequest{}
	mi := &file_core_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryQueryRequest) ProtoMessage() {}

func (x *MediaLibraryQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryQueryRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryQueryRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{11}
}

func (x *MediaLibraryQueryRequest) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *MediaLibraryQueryRequest) GetAddBase64() bool {
	if x != nil {
		return x.AddBase64
	}
	return false
}

func (x *MediaLibraryQueryRequest) GetIsFile() bool {
	if x != nil {
		return x.IsFile
	}
	return false
}

func (x *MediaLibraryQueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type MediaLibraryUploadFromUrlRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileUrl          string                 `protobuf:"bytes,1,opt,name=fileUrl,proto3" json:"fileUrl,omitempty"`
	MediaLibraryPath string                 `protobuf:"bytes,2,opt,name=mediaLibraryPath,proto3" json:"mediaLibraryPath,omitempty"`
	SaveFileName     string                 `protobuf:"bytes,3,opt,name=saveFileName,proto3" json:"saveFileName,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaLibraryUploadFromUrlRequest) Reset() {
	*x = MediaLibraryUploadFromUrlRequest{}
	mi := &file_core_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryUploadFromUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryUploadFromUrlRequest) ProtoMessage() {}

func (x *MediaLibraryUploadFromUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryUploadFromUrlRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryUploadFromUrlRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{12}
}

func (x *MediaLibraryUploadFromUrlRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetMediaLibraryPath() string {
	if x != nil {
		return x.MediaLibraryPath
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetSaveFileName() string {
	if x != nil {
		return x.SaveFileName
	}
	return ""
}

func (x *MediaLibraryUploadFromUrlRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type MediaLibraryUploadFromBase64Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Base64Str        string                 `protobuf:"bytes,1,opt,name=base64Str,proto3" json:"base64Str,omitempty"`
	MediaLibraryPath string                 `protobuf:"bytes,2,opt,name=mediaLibraryPath,proto3" json:"mediaLibraryPath,omitempty"`
	SaveFileName     string                 `protobuf:"bytes,3,opt,name=saveFileName,proto3" json:"saveFileName,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaLibraryUploadFromBase64Request) Reset() {
	*x = MediaLibraryUploadFromBase64Request{}
	mi := &file_core_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryUploadFromBase64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryUploadFromBase64Request) ProtoMessage() {}

func (x *MediaLibraryUploadFromBase64Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryUploadFromBase64Request.ProtoReflect.Descriptor instead.
func (*MediaLibraryUploadFromBase64Request) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{13}
}

func (x *MediaLibraryUploadFromBase64Request) GetBase64Str() string {
	if x != nil {
		return x.Base64Str
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetMediaLibraryPath() string {
	if x != nil {
		return x.MediaLibraryPath
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetSaveFileName() string {
	if x != nil {
		return x.SaveFileName
	}
	return ""
}

func (x *MediaLibraryUploadFromBase64Request) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type MediaLibraryDirSettingQueryByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryDirSettingQueryByPathRequest) Reset() {
	*x = MediaLibraryDirSettingQueryByPathRequest{}
	mi := &file_core_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDirSettingQueryByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDirSettingQueryByPathRequest) ProtoMessage() {}

func (x *MediaLibraryDirSettingQueryByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDirSettingQueryByPathRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDirSettingQueryByPathRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{14}
}

func (x *MediaLibraryDirSettingQueryByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MediaLibraryDirMkDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaLibraryDirMkDirRequest) Reset() {
	*x = MediaLibraryDirMkDirRequest{}
	mi := &file_core_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDirMkDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDirMkDirRequest) ProtoMessage() {}

func (x *MediaLibraryDirMkDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDirMkDirRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDirMkDirRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{15}
}

func (x *MediaLibraryDirMkDirRequest) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *MediaLibraryDirMkDirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaLibraryDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Files          []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	CompleteDelete bool                   `protobuf:"varint,2,opt,name=completeDelete,proto3" json:"completeDelete,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaLibraryDeleteRequest) Reset() {
	*x = MediaLibraryDeleteRequest{}
	mi := &file_core_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaLibraryDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaLibraryDeleteRequest) ProtoMessage() {}

func (x *MediaLibraryDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaLibraryDeleteRequest.ProtoReflect.Descriptor instead.
func (*MediaLibraryDeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_core_proto_rawDescGZIP(), []int{16}
}

func (x *MediaLibraryDeleteRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MediaLibraryDeleteRequest) GetCompleteDelete() bool {
	if x != nil {
		return x.CompleteDelete
	}
	return false
}

var File_core_core_proto protoreflect.FileDescriptor

const file_core_core_proto_rawDesc = "" +
	"\n" +
	"\x0fcore/core.proto\x12\x04core\x1a\rapi/api.proto\"@\n" +
	"\x10GetDeviceRequest\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"j\n" +
	"\x14GetDataDeviceRequest\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"$\n" +
	"\x0eGetRequestName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\x10QueryDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\">\n" +
	"\x16GetOrDeleteDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"q\n" +
	"\x11UpdateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x04 \x01(\bR\fcloseRequire\"|\n" +
	"\x16MultiUpdateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x04 \x01(\bR\fcloseRequire\"a\n" +
	"\x11CreateDataRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\"\n" +
	"\fcloseRequire\x18\x03 \x01(\bR\fcloseRequire\"(\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x80\x01\n" +
	"\x18MediaLibraryQueryRequest\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x1c\n" +
	"\taddBase64\x18\x02 \x01(\bR\taddBase64\x12\x16\n" +
	"\x06isFile\x18\x03 \x01(\bR\x06isFile\x12\x14\n" +
	"\x05query\x18\x04 \x01(\fR\x05query\"\xa4\x01\n" +
	" MediaLibraryUploadFromUrlRequest\x12\x18\n" +
	"\afileUrl\x18\x01 \x01(\tR\afileUrl\x12*\n" +
	"\x10mediaLibraryPath\x18\x02 \x01(\tR\x10mediaLibraryPath\x12\"\n" +
	"\fsaveFileName\x18\x03 \x01(\tR\fsaveFileName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\xab\x01\n" +
	"#MediaLibraryUploadFromBase64Request\x12\x1c\n" +
	"\tbase64Str\x18\x01 \x01(\tR\tbase64Str\x12*\n" +
	"\x10mediaLibraryPath\x18\x02 \x01(\tR\x10mediaLibraryPath\x12\"\n" +
	"\fsaveFileName\x18\x03 \x01(\tR\fsaveFileName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\">\n" +
	"(MediaLibraryDirSettingQueryByPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"K\n" +
	"\x1bMediaLibraryDirMkDirRequest\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Y\n" +
	"\x19MediaLibraryDeleteRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12&\n" +
	"\x0ecompleteDelete\x18\x02 \x01(\bR\x0ecompleteDelete2\xaa\x02\n" +
	"\x0eLicenseService\x124\n" +
	"\x0eGetFileLicense\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"UseLicense\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x125\n" +
	"\x0fFindMachineCode\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12<\n" +
	"\x10GetDriverLicense\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\rUploadLicense\x12\x17.core.UploadFileRequest\x1a\r.api.Response\"\x00(\x012\x9a\x01\n" +
	"\n" +
	"AppService\x12.\n" +
	"\bGetToken\x12\x11.api.TokenRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002\x8f\x02\n" +
	"\n" +
	"LogService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x128\n" +
	"\x12QueryApiPermission\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\x13CreateApiPermission\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\x81\x05\n" +
	"\vUserService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12=\n" +
	"\x12GetCurrentUserInfo\x12\x16.core.LoginUserRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\x14UserPermissionUpdate\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x121\n" +
	"\vQueryBackup\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\x10DeleteManyBackup\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\x10CreateManyBackup\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\vCallAIModel\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xa8\x05\n" +
	"\x12TableSchemaService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12F\n" +
	"\x1bQueryDeviceByDriverAndGroup\x12\x16.core.GetDeviceRequest\x1a\r.api.Response\"\x00\x12K\n" +
	" QueryTableDeviceByDriverAndGroup\x12\x16.core.GetDeviceRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\n" +
	"FindDevice\x12\x1a.core.GetDataDeviceRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\rQueryEmulator\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\n" +
	"StatsQuery\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\x0fFindCommandByID\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002\xc3\n" +
	"\n" +
	"\x10TableDataService\x120\n" +
	"\x05Query\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x0eQueryByTableId\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x03Get\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\x06Delete\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x125\n" +
	"\n" +
	"DeleteMany\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Update\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x123\n" +
	"\aReplace\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Create\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"CreateMany\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12A\n" +
	"\x1aFindTableDataDeptByDeptIDs\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\n" +
	"UpdateMany\x12\x1c.core.MultiUpdateDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x13GetWarningFilterIDs\x12\x11.api.EmptyRequest\x1a\r.api.Response\"\x00\x12<\n" +
	"\vFindTagByID\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x12@\n" +
	"\x0fFindCommandByID\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\tQueryByDB\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x128\n" +
	"\aGetByDB\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x12;\n" +
	"\n" +
	"DeleteByDB\x12\x1c.core.GetOrDeleteDataRequest\x1a\r.api.Response\"\x00\x129\n" +
	"\x0eDeleteManyByDB\x12\x16.core.QueryDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"UpdateByDB\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x127\n" +
	"\vReplaceByDB\x12\x17.core.UpdateDataRequest\x1a\r.api.Response\"\x00\x126\n" +
	"\n" +
	"CreateByDB\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12:\n" +
	"\x0eCreateManyByDB\x12\x17.core.CreateDataRequest\x1a\r.api.Response\"\x00\x12?\n" +
	"\x0eUpdateManyByDB\x12\x1c.core.MultiUpdateDataRequest\x1a\r.api.Response\"\x002\xb4\x02\n" +
	"\x12TableRecordService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002l\n" +
	"\x0eMessageService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002n\n" +
	"\x10DashboardService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xa7\x01\n" +
	"\x10DataQueryService\x121\n" +
	"\n" +
	"PostLatest\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\bGetQuery\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x120\n" +
	"\tPostQuery\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xa1\x01\n" +
	"\vRoleService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x0eAdminRoleCheck\x12\x11.api.EmptyRequest\x1a\r.api.Response\"\x002n\n" +
	"\x0eCatalogService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002k\n" +
	"\vDeptService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x002=\n" +
	"\x0eSettingService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x002\xb7\x02\n" +
	"\x15SystemVariableService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xa7\x03\n" +
	"\rBackupService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12,\n" +
	"\x06Import\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12,\n" +
	"\x06Export\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x124\n" +
	"\x06Upload\x12\x17.core.UploadFileRequest\x1a\r.api.Response\"\x00(\x01\x12C\n" +
	"\bDownload\x12\x17.api.GetOrDeleteRequest\x1a\x1a.core.DownloadFileResponse\"\x000\x012\xb4\x02\n" +
	"\x12TaskManagerService\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x002\xe7\x02\n" +
	"\x13MediaLibraryService\x128\n" +
	"\x05Query\x12\x1e.core.MediaLibraryQueryRequest\x1a\r.api.Response\"\x00\x12H\n" +
	"\rUploadFromUrl\x12&.core.MediaLibraryUploadFromUrlRequest\x1a\r.api.Response\"\x00\x12N\n" +
	"\x10UploadFromBase64\x12).core.MediaLibraryUploadFromBase64Request\x1a\r.api.Response\"\x00\x12;\n" +
	"\x05Mkdir\x12!.core.MediaLibraryDirMkDirRequest\x1a\r.api.Response\"\x00\x12?\n" +
	"\vDeleteFiles\x12\x1f.core.MediaLibraryDeleteRequest\x1a\r.api.Response\"\x002\x8d\x03\n" +
	"\x1dMediaLibraryDirSettingService\x12-\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\r.api.Response\"\x00\x122\n" +
	"\x06Delete\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12-\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12.\n" +
	"\aReplace\x12\x12.api.UpdateRequest\x1a\r.api.Response\"\x00\x12/\n" +
	"\x03Get\x12\x17.api.GetOrDeleteRequest\x1a\r.api.Response\"\x00\x12L\n" +
	"\tGetByPath\x12..core.MediaLibraryDirSettingQueryByPathRequest\x1a\r.api.Response\"\x00\x12+\n" +
	"\x05Query\x12\x11.api.QueryRequest\x1a\r.api.Response\"\x00B;\n" +
	"$cn.airiot.sdk.client.dubbo.grpc.coreP\x01Z\v./core;core\x88\x01\x01\xa0\x01\x01b\x06proto3"

var (
	file_core_core_proto_rawDescOnce sync.Once
	file_core_core_proto_rawDescData []byte
)

func file_core_core_proto_rawDescGZIP() []byte {
	file_core_core_proto_rawDescOnce.Do(func() {
		file_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_core_proto_rawDesc), len(file_core_core_proto_rawDesc)))
	})
	return file_core_core_proto_rawDescData
}

var file_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_core_core_proto_goTypes = []any{
	(*GetDeviceRequest)(nil),                         // 0: core.GetDeviceRequest
	(*GetDataDeviceRequest)(nil),                     // 1: core.GetDataDeviceRequest
	(*GetRequestName)(nil),                           // 2: core.GetRequestName
	(*QueryDataRequest)(nil),                         // 3: core.QueryDataRequest
	(*GetOrDeleteDataRequest)(nil),                   // 4: core.GetOrDeleteDataRequest
	(*UpdateDataRequest)(nil),                        // 5: core.UpdateDataRequest
	(*MultiUpdateDataRequest)(nil),                   // 6: core.MultiUpdateDataRequest
	(*CreateDataRequest)(nil),                        // 7: core.CreateDataRequest
	(*LoginUserRequest)(nil),                         // 8: core.LoginUserRequest
	(*UploadFileRequest)(nil),                        // 9: core.UploadFileRequest
	(*DownloadFileResponse)(nil),                     // 10: core.DownloadFileResponse
	(*MediaLibraryQueryRequest)(nil),                 // 11: core.MediaLibraryQueryRequest
	(*MediaLibraryUploadFromUrlRequest)(nil),         // 12: core.MediaLibraryUploadFromUrlRequest
	(*MediaLibraryUploadFromBase64Request)(nil),      // 13: core.MediaLibraryUploadFromBase64Request
	(*MediaLibraryDirSettingQueryByPathRequest)(nil), // 14: core.MediaLibraryDirSettingQueryByPathRequest
	(*MediaLibraryDirMkDirRequest)(nil),              // 15: core.MediaLibraryDirMkDirRequest
	(*MediaLibraryDeleteRequest)(nil),                // 16: core.MediaLibraryDeleteRequest
	(*api.QueryRequest)(nil),                         // 17: api.QueryRequest
	(*api.GetOrDeleteRequest)(nil),                   // 18: api.GetOrDeleteRequest
	(*api.TokenRequest)(nil),                         // 19: api.TokenRequest
	(*api.CreateRequest)(nil),                        // 20: api.CreateRequest
	(*api.UpdateRequest)(nil),                        // 21: api.UpdateRequest
	(*api.EmptyRequest)(nil),                         // 22: api.EmptyRequest
	(*api.Response)(nil),                             // 23: api.Response
}
var file_core_core_proto_depIdxs = []int32{
	17,  // 0: core.LicenseService.GetFileLicense:input_type -> api.QueryRequest
	17,  // 1: core.LicenseService.UseLicense:input_type -> api.QueryRequest
	17,  // 2: core.LicenseService.FindMachineCode:input_type -> api.QueryRequest
	18,  // 3: core.LicenseService.GetDriverLicense:input_type -> api.GetOrDeleteRequest
	9,   // 4: core.LicenseService.UploadLicense:input_type -> core.UploadFileRequest
	19,  // 5: core.AppService.GetToken:input_type -> api.TokenRequest
	17,  // 6: core.AppService.Query:input_type -> api.QueryRequest
	18,  // 7: core.AppService.Get:input_type -> api.GetOrDeleteRequest
	20,  // 8: core.LogService.Create:input_type -> api.CreateRequest
	18,  // 9: core.LogService.Get:input_type -> api.GetOrDeleteRequest
	17,  // 10: core.LogService.Query:input_type -> api.QueryRequest
	17,  // 11: core.LogService.QueryApiPermission:input_type -> api.QueryRequest
	20,  // 12: core.LogService.CreateApiPermission:input_type -> api.CreateRequest
	17,  // 13: core.UserService.Query:input_type -> api.QueryRequest
	18,  // 14: core.UserService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 15: core.UserService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 16: core.UserService.Update:input_type -> api.UpdateRequest
	21,  // 17: core.UserService.Replace:input_type -> api.UpdateRequest
	20,  // 18: core.UserService.Create:input_type -> api.CreateRequest
	8,   // 19: core.UserService.GetCurrentUserInfo:input_type -> core.LoginUserRequest
	20,  // 20: core.UserService.UserPermissionUpdate:input_type -> api.CreateRequest
	17,  // 21: core.UserService.QueryBackup:input_type -> api.QueryRequest
	17,  // 22: core.UserService.DeleteManyBackup:input_type -> api.QueryRequest
	20,  // 23: core.UserService.CreateManyBackup:input_type -> api.CreateRequest
	20,  // 24: core.UserService.CallAIModel:input_type -> api.CreateRequest
	17,  // 25: core.TableSchemaService.Query:input_type -> api.QueryRequest
	0,   // 26: core.TableSchemaService.QueryDeviceByDriverAndGroup:input_type -> core.GetDeviceRequest
	0,   // 27: core.TableSchemaService.QueryTableDeviceByDriverAndGroup:input_type -> core.GetDeviceRequest
	1,   // 28: core.TableSchemaService.FindDevice:input_type -> core.GetDataDeviceRequest
	17,  // 29: core.TableSchemaService.QueryEmulator:input_type -> api.QueryRequest
	18,  // 30: core.TableSchemaService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 31: core.TableSchemaService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 32: core.TableSchemaService.Update:input_type -> api.UpdateRequest
	21,  // 33: core.TableSchemaService.Replace:input_type -> api.UpdateRequest
	20,  // 34: core.TableSchemaService.Create:input_type -> api.CreateRequest
	17,  // 35: core.TableSchemaService.StatsQuery:input_type -> api.QueryRequest
	18,  // 36: core.TableSchemaService.FindCommandByID:input_type -> api.GetOrDeleteRequest
	3,   // 37: core.TableDataService.Query:input_type -> core.QueryDataRequest
	3,   // 38: core.TableDataService.QueryByTableId:input_type -> core.QueryDataRequest
	4,   // 39: core.TableDataService.Get:input_type -> core.GetOrDeleteDataRequest
	4,   // 40: core.TableDataService.Delete:input_type -> core.GetOrDeleteDataRequest
	3,   // 41: core.TableDataService.DeleteMany:input_type -> core.QueryDataRequest
	5,   // 42: core.TableDataService.Update:input_type -> core.UpdateDataRequest
	5,   // 43: core.TableDataService.Replace:input_type -> core.UpdateDataRequest
	7,   // 44: core.TableDataService.Create:input_type -> core.CreateDataRequest
	7,   // 45: core.TableDataService.CreateMany:input_type -> core.CreateDataRequest
	20,  // 46: core.TableDataService.FindTableDataDeptByDeptIDs:input_type -> api.CreateRequest
	6,   // 47: core.TableDataService.UpdateMany:input_type -> core.MultiUpdateDataRequest
	22,  // 48: core.TableDataService.GetWarningFilterIDs:input_type -> api.EmptyRequest
	4,   // 49: core.TableDataService.FindTagByID:input_type -> core.GetOrDeleteDataRequest
	4,   // 50: core.TableDataService.FindCommandByID:input_type -> core.GetOrDeleteDataRequest
	3,   // 51: core.TableDataService.QueryByDB:input_type -> core.QueryDataRequest
	4,   // 52: core.TableDataService.GetByDB:input_type -> core.GetOrDeleteDataRequest
	4,   // 53: core.TableDataService.DeleteByDB:input_type -> core.GetOrDeleteDataRequest
	3,   // 54: core.TableDataService.DeleteManyByDB:input_type -> core.QueryDataRequest
	5,   // 55: core.TableDataService.UpdateByDB:input_type -> core.UpdateDataRequest
	5,   // 56: core.TableDataService.ReplaceByDB:input_type -> core.UpdateDataRequest
	7,   // 57: core.TableDataService.CreateByDB:input_type -> core.CreateDataRequest
	7,   // 58: core.TableDataService.CreateManyByDB:input_type -> core.CreateDataRequest
	6,   // 59: core.TableDataService.UpdateManyByDB:input_type -> core.MultiUpdateDataRequest
	17,  // 60: core.TableRecordService.Query:input_type -> api.QueryRequest
	18,  // 61: core.TableRecordService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 62: core.TableRecordService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 63: core.TableRecordService.Update:input_type -> api.UpdateRequest
	21,  // 64: core.TableRecordService.Replace:input_type -> api.UpdateRequest
	20,  // 65: core.TableRecordService.Create:input_type -> api.CreateRequest
	20,  // 66: core.MessageService.Create:input_type -> api.CreateRequest
	17,  // 67: core.MessageService.Query:input_type -> api.QueryRequest
	20,  // 68: core.DashboardService.Create:input_type -> api.CreateRequest
	17,  // 69: core.DashboardService.Query:input_type -> api.QueryRequest
	20,  // 70: core.DataQueryService.PostLatest:input_type -> api.CreateRequest
	17,  // 71: core.DataQueryService.GetQuery:input_type -> api.QueryRequest
	20,  // 72: core.DataQueryService.PostQuery:input_type -> api.CreateRequest
	17,  // 73: core.RoleService.Query:input_type -> api.QueryRequest
	18,  // 74: core.RoleService.Get:input_type -> api.GetOrDeleteRequest
	22,  // 75: core.RoleService.AdminRoleCheck:input_type -> api.EmptyRequest
	17,  // 76: core.CatalogService.Query:input_type -> api.QueryRequest
	18,  // 77: core.CatalogService.Get:input_type -> api.GetOrDeleteRequest
	17,  // 78: core.DeptService.Query:input_type -> api.QueryRequest
	18,  // 79: core.DeptService.Get:input_type -> api.GetOrDeleteRequest
	17,  // 80: core.SettingService.Query:input_type -> api.QueryRequest
	17,  // 81: core.SystemVariableService.Query:input_type -> api.QueryRequest
	18,  // 82: core.SystemVariableService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 83: core.SystemVariableService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 84: core.SystemVariableService.Update:input_type -> api.UpdateRequest
	21,  // 85: core.SystemVariableService.Replace:input_type -> api.UpdateRequest
	20,  // 86: core.SystemVariableService.Create:input_type -> api.CreateRequest
	17,  // 87: core.BackupService.Query:input_type -> api.QueryRequest
	18,  // 88: core.BackupService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 89: core.BackupService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 90: core.BackupService.Update:input_type -> api.UpdateRequest
	17,  // 91: core.BackupService.Import:input_type -> api.QueryRequest
	17,  // 92: core.BackupService.Export:input_type -> api.QueryRequest
	9,   // 93: core.BackupService.Upload:input_type -> core.UploadFileRequest
	18,  // 94: core.BackupService.Download:input_type -> api.GetOrDeleteRequest
	17,  // 95: core.TaskManagerService.Query:input_type -> api.QueryRequest
	18,  // 96: core.TaskManagerService.Get:input_type -> api.GetOrDeleteRequest
	18,  // 97: core.TaskManagerService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 98: core.TaskManagerService.Update:input_type -> api.UpdateRequest
	21,  // 99: core.TaskManagerService.Replace:input_type -> api.UpdateRequest
	20,  // 100: core.TaskManagerService.Create:input_type -> api.CreateRequest
	11,  // 101: core.MediaLibraryService.Query:input_type -> core.MediaLibraryQueryRequest
	12,  // 102: core.MediaLibraryService.UploadFromUrl:input_type -> core.MediaLibraryUploadFromUrlRequest
	13,  // 103: core.MediaLibraryService.UploadFromBase64:input_type -> core.MediaLibraryUploadFromBase64Request
	15,  // 104: core.MediaLibraryService.Mkdir:input_type -> core.MediaLibraryDirMkDirRequest
	16,  // 105: core.MediaLibraryService.DeleteFiles:input_type -> core.MediaLibraryDeleteRequest
	20,  // 106: core.MediaLibraryDirSettingService.Create:input_type -> api.CreateRequest
	18,  // 107: core.MediaLibraryDirSettingService.Delete:input_type -> api.GetOrDeleteRequest
	21,  // 108: core.MediaLibraryDirSettingService.Update:input_type -> api.UpdateRequest
	21,  // 109: core.MediaLibraryDirSettingService.Replace:input_type -> api.UpdateRequest
	18,  // 110: core.MediaLibraryDirSettingService.Get:input_type -> api.GetOrDeleteRequest
	14,  // 111: core.MediaLibraryDirSettingService.GetByPath:input_type -> core.MediaLibraryDirSettingQueryByPathRequest
	17,  // 112: core.MediaLibraryDirSettingService.Query:input_type -> api.QueryRequest
	23,  // 113: core.LicenseService.GetFileLicense:output_type -> api.Response
	23,  // 114: core.LicenseService.UseLicense:output_type -> api.Response
	23,  // 115: core.LicenseService.FindMachineCode:output_type -> api.Response
	23,  // 116: core.LicenseService.GetDriverLicense:output_type -> api.Response
	23,  // 117: core.LicenseService.UploadLicense:output_type -> api.Response
	23,  // 118: core.AppService.GetToken:output_type -> api.Response
	23,  // 119: core.AppService.Query:output_type -> api.Response
	23,  // 120: core.AppService.Get:output_type -> api.Response
	23,  // 121: core.LogService.Create:output_type -> api.Response
	23,  // 122: core.LogService.Get:output_type -> api.Response
	23,  // 123: core.LogService.Query:output_type -> api.Response
	23,  // 124: core.LogService.QueryApiPermission:output_type -> api.Response
	23,  // 125: core.LogService.CreateApiPermission:output_type -> api.Response
	23,  // 126: core.UserService.Query:output_type -> api.Response
	23,  // 127: core.UserService.Get:output_type -> api.Response
	23,  // 128: core.UserService.Delete:output_type -> api.Response
	23,  // 129: core.UserService.Update:output_type -> api.Response
	23,  // 130: core.UserService.Replace:output_type -> api.Response
	23,  // 131: core.UserService.Create:output_type -> api.Response
	23,  // 132: core.UserService.GetCurrentUserInfo:output_type -> api.Response
	23,  // 133: core.UserService.UserPermissionUpdate:output_type -> api.Response
	23,  // 134: core.UserService.QueryBackup:output_type -> api.Response
	23,  // 135: core.UserService.DeleteManyBackup:output_type -> api.Response
	23,  // 136: core.UserService.CreateManyBackup:output_type -> api.Response
	23,  // 137: core.UserService.CallAIModel:output_type -> api.Response
	23,  // 138: core.TableSchemaService.Query:output_type -> api.Response
	23,  // 139: core.TableSchemaService.QueryDeviceByDriverAndGroup:output_type -> api.Response
	23,  // 140: core.TableSchemaService.QueryTableDeviceByDriverAndGroup:output_type -> api.Response
	23,  // 141: core.TableSchemaService.FindDevice:output_type -> api.Response
	23,  // 142: core.TableSchemaService.QueryEmulator:output_type -> api.Response
	23,  // 143: core.TableSchemaService.Get:output_type -> api.Response
	23,  // 144: core.TableSchemaService.Delete:output_type -> api.Response
	23,  // 145: core.TableSchemaService.Update:output_type -> api.Response
	23,  // 146: core.TableSchemaService.Replace:output_type -> api.Response
	23,  // 147: core.TableSchemaService.Create:output_type -> api.Response
	23,  // 148: core.TableSchemaService.StatsQuery:output_type -> api.Response
	23,  // 149: core.TableSchemaService.FindCommandByID:output_type -> api.Response
	23,  // 150: core.TableDataService.Query:output_type -> api.Response
	23,  // 151: core.TableDataService.QueryByTableId:output_type -> api.Response
	23,  // 152: core.TableDataService.Get:output_type -> api.Response
	23,  // 153: core.TableDataService.Delete:output_type -> api.Response
	23,  // 154: core.TableDataService.DeleteMany:output_type -> api.Response
	23,  // 155: core.TableDataService.Update:output_type -> api.Response
	23,  // 156: core.TableDataService.Replace:output_type -> api.Response
	23,  // 157: core.TableDataService.Create:output_type -> api.Response
	23,  // 158: core.TableDataService.CreateMany:output_type -> api.Response
	23,  // 159: core.TableDataService.FindTableDataDeptByDeptIDs:output_type -> api.Response
	23,  // 160: core.TableDataService.UpdateMany:output_type -> api.Response
	23,  // 161: core.TableDataService.GetWarningFilterIDs:output_type -> api.Response
	23,  // 162: core.TableDataService.FindTagByID:output_type -> api.Response
	23,  // 163: core.TableDataService.FindCommandByID:output_type -> api.Response
	23,  // 164: core.TableDataService.QueryByDB:output_type -> api.Response
	23,  // 165: core.TableDataService.GetByDB:output_type -> api.Response
	23,  // 166: core.TableDataService.DeleteByDB:output_type -> api.Response
	23,  // 167: core.TableDataService.DeleteManyByDB:output_type -> api.Response
	23,  // 168: core.TableDataService.UpdateByDB:output_type -> api.Response
	23,  // 169: core.TableDataService.ReplaceByDB:output_type -> api.Response
	23,  // 170: core.TableDataService.CreateByDB:output_type -> api.Response
	23,  // 171: core.TableDataService.CreateManyByDB:output_type -> api.Response
	23,  // 172: core.TableDataService.UpdateManyByDB:output_type -> api.Response
	23,  // 173: core.TableRecordService.Query:output_type -> api.Response
	23,  // 174: core.TableRecordService.Get:output_type -> api.Response
	23,  // 175: core.TableRecordService.Delete:output_type -> api.Response
	23,  // 176: core.TableRecordService.Update:output_type -> api.Response
	23,  // 177: core.TableRecordService.Replace:output_type -> api.Response
	23,  // 178: core.TableRecordService.Create:output_type -> api.Response
	23,  // 179: core.MessageService.Create:output_type -> api.Response
	23,  // 180: core.MessageService.Query:output_type -> api.Response
	23,  // 181: core.DashboardService.Create:output_type -> api.Response
	23,  // 182: core.DashboardService.Query:output_type -> api.Response
	23,  // 183: core.DataQueryService.PostLatest:output_type -> api.Response
	23,  // 184: core.DataQueryService.GetQuery:output_type -> api.Response
	23,  // 185: core.DataQueryService.PostQuery:output_type -> api.Response
	23,  // 186: core.RoleService.Query:output_type -> api.Response
	23,  // 187: core.RoleService.Get:output_type -> api.Response
	23,  // 188: core.RoleService.AdminRoleCheck:output_type -> api.Response
	23,  // 189: core.CatalogService.Query:output_type -> api.Response
	23,  // 190: core.CatalogService.Get:output_type -> api.Response
	23,  // 191: core.DeptService.Query:output_type -> api.Response
	23,  // 192: core.DeptService.Get:output_type -> api.Response
	23,  // 193: core.SettingService.Query:output_type -> api.Response
	23,  // 194: core.SystemVariableService.Query:output_type -> api.Response
	23,  // 195: core.SystemVariableService.Get:output_type -> api.Response
	23,  // 196: core.SystemVariableService.Delete:output_type -> api.Response
	23,  // 197: core.SystemVariableService.Update:output_type -> api.Response
	23,  // 198: core.SystemVariableService.Replace:output_type -> api.Response
	23,  // 199: core.SystemVariableService.Create:output_type -> api.Response
	23,  // 200: core.BackupService.Query:output_type -> api.Response
	23,  // 201: core.BackupService.Get:output_type -> api.Response
	23,  // 202: core.BackupService.Delete:output_type -> api.Response
	23,  // 203: core.BackupService.Update:output_type -> api.Response
	23,  // 204: core.BackupService.Import:output_type -> api.Response
	23,  // 205: core.BackupService.Export:output_type -> api.Response
	23,  // 206: core.BackupService.Upload:output_type -> api.Response
	10,  // 207: core.BackupService.Download:output_type -> core.DownloadFileResponse
	23,  // 208: core.TaskManagerService.Query:output_type -> api.Response
	23,  // 209: core.TaskManagerService.Get:output_type -> api.Response
	23,  // 210: core.TaskManagerService.Delete:output_type -> api.Response
	23,  // 211: core.TaskManagerService.Update:output_type -> api.Response
	23,  // 212: core.TaskManagerService.Replace:output_type -> api.Response
	23,  // 213: core.TaskManagerService.Create:output_type -> api.Response
	23,  // 214: core.MediaLibraryService.Query:output_type -> api.Response
	23,  // 215: core.MediaLibraryService.UploadFromUrl:output_type -> api.Response
	23,  // 216: core.MediaLibraryService.UploadFromBase64:output_type -> api.Response
	23,  // 217: core.MediaLibraryService.Mkdir:output_type -> api.Response
	23,  // 218: core.MediaLibraryService.DeleteFiles:output_type -> api.Response
	23,  // 219: core.MediaLibraryDirSettingService.Create:output_type -> api.Response
	23,  // 220: core.MediaLibraryDirSettingService.Delete:output_type -> api.Response
	23,  // 221: core.MediaLibraryDirSettingService.Update:output_type -> api.Response
	23,  // 222: core.MediaLibraryDirSettingService.Replace:output_type -> api.Response
	23,  // 223: core.MediaLibraryDirSettingService.Get:output_type -> api.Response
	23,  // 224: core.MediaLibraryDirSettingService.GetByPath:output_type -> api.Response
	23,  // 225: core.MediaLibraryDirSettingService.Query:output_type -> api.Response
	113, // [113:226] is the sub-list for method output_type
	0,   // [0:113] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_core_core_proto_init() }
func file_core_core_proto_init() {
	if File_core_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_proto_rawDesc), len(file_core_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   19,
		},
		GoTypes:           file_core_core_proto_goTypes,
		DependencyIndexes: file_core_core_proto_depIdxs,
		MessageInfos:      file_core_core_proto_msgTypes,
	}.Build()
	File_core_core_proto = out.File
	file_core_core_proto_goTypes = nil
	file_core_core_proto_depIdxs = nil
}
