// Copyright 2015 The gRPC Authors

// protoc -I ./ --go_out=. ./record/record.proto
// protoc -I ./ --go-grpc_out=. record/record.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: record/record.proto

package record

import (
	api "github.com/air-iot/api-client-go/v4/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 删除报警录制相关信息. 同时删除报警录制的视频和抓图信息
type DeleteWarningRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 报警ID
	WarningId string `protobuf:"bytes,1,opt,name=warningId,proto3" json:"warningId,omitempty"`
	// 是否删除录制视频和抓图
	DeleteFiles   bool `protobuf:"varint,2,opt,name=deleteFiles,proto3" json:"deleteFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarningRecordRequest) Reset() {
	*x = DeleteWarningRecordRequest{}
	mi := &file_record_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarningRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarningRecordRequest) ProtoMessage() {}

func (x *DeleteWarningRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarningRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteWarningRecordRequest) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteWarningRecordRequest) GetWarningId() string {
	if x != nil {
		return x.WarningId
	}
	return ""
}

func (x *DeleteWarningRecordRequest) GetDeleteFiles() bool {
	if x != nil {
		return x.DeleteFiles
	}
	return false
}

var File_record_record_proto protoreflect.FileDescriptor

const file_record_record_proto_rawDesc = "" +
	"\n" +
	"\x13record/record.proto\x12\x06record\x1a\rapi/api.proto\"\\\n" +
	"\x1aDeleteWarningRecordRequest\x12\x1c\n" +
	"\twarningId\x18\x01 \x01(\tR\twarningId\x12 \n" +
	"\vdeleteFiles\x18\x02 \x01(\bR\vdeleteFiles2\xf0\x01\n" +
	"\rRecordService\x12D\n" +
	"\rDeleteWarning\x12\".record.DeleteWarningRecordRequest\x1a\r.api.Response\"\x00\x12L\n" +
	"\x15DeleteWarningPlayback\x12\".record.DeleteWarningRecordRequest\x1a\r.api.Response\"\x00\x12K\n" +
	"\x14DeleteWarningCapture\x12\".record.DeleteWarningRecordRequest\x1a\r.api.Response\"\x00B\x11Z\x0f./record;recordb\x06proto3"

var (
	file_record_record_proto_rawDescOnce sync.Once
	file_record_record_proto_rawDescData []byte
)

func file_record_record_proto_rawDescGZIP() []byte {
	file_record_record_proto_rawDescOnce.Do(func() {
		file_record_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_record_proto_rawDesc), len(file_record_record_proto_rawDesc)))
	})
	return file_record_record_proto_rawDescData
}

var file_record_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_record_record_proto_goTypes = []any{
	(*DeleteWarningRecordRequest)(nil), // 0: record.DeleteWarningRecordRequest
	(*api.Response)(nil),               // 1: api.Response
}
var file_record_record_proto_depIdxs = []int32{
	0, // 0: record.RecordService.DeleteWarning:input_type -> record.DeleteWarningRecordRequest
	0, // 1: record.RecordService.DeleteWarningPlayback:input_type -> record.DeleteWarningRecordRequest
	0, // 2: record.RecordService.DeleteWarningCapture:input_type -> record.DeleteWarningRecordRequest
	1, // 3: record.RecordService.DeleteWarning:output_type -> api.Response
	1, // 4: record.RecordService.DeleteWarningPlayback:output_type -> api.Response
	1, // 5: record.RecordService.DeleteWarningCapture:output_type -> api.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_record_record_proto_init() }
func file_record_record_proto_init() {
	if File_record_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_record_proto_rawDesc), len(file_record_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_record_record_proto_goTypes,
		DependencyIndexes: file_record_record_proto_depIdxs,
		MessageInfos:      file_record_record_proto_msgTypes,
	}.Build()
	File_record_record_proto = out.File
	file_record_record_proto_goTypes = nil
	file_record_record_proto_depIdxs = nil
}
