// Copyright 2015 The gRPC Authors

// protoc -I ./ --go_out=. ./record/record.proto
// protoc -I ./ --go-grpc_out=. record/record.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: record/record.proto

package record

import (
	context "context"
	api "github.com/air-iot/api-client-go/v4/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordService_DeleteWarning_FullMethodName         = "/record.RecordService/DeleteWarning"
	RecordService_DeleteWarningPlayback_FullMethodName = "/record.RecordService/DeleteWarningPlayback"
	RecordService_DeleteWarningCapture_FullMethodName  = "/record.RecordService/DeleteWarningCapture"
)

// RecordServiceClient is the client API for RecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordServiceClient interface {
	// 删除报警录制相关信息. 包括录制视频和抓图信息
	DeleteWarning(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error)
	// 删除报警录制视频信息
	DeleteWarningPlayback(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error)
	// 删除报警录制抓图信息
	DeleteWarningCapture(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type recordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordServiceClient(cc grpc.ClientConnInterface) RecordServiceClient {
	return &recordServiceClient{cc}
}

func (c *recordServiceClient) DeleteWarning(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, RecordService_DeleteWarning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteWarningPlayback(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, RecordService_DeleteWarningPlayback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteWarningCapture(ctx context.Context, in *DeleteWarningRecordRequest, opts ...grpc.CallOption) (*api.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.Response)
	err := c.cc.Invoke(ctx, RecordService_DeleteWarningCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServiceServer is the server API for RecordService service.
// All implementations must embed UnimplementedRecordServiceServer
// for forward compatibility.
type RecordServiceServer interface {
	// 删除报警录制相关信息. 包括录制视频和抓图信息
	DeleteWarning(context.Context, *DeleteWarningRecordRequest) (*api.Response, error)
	// 删除报警录制视频信息
	DeleteWarningPlayback(context.Context, *DeleteWarningRecordRequest) (*api.Response, error)
	// 删除报警录制抓图信息
	DeleteWarningCapture(context.Context, *DeleteWarningRecordRequest) (*api.Response, error)
	mustEmbedUnimplementedRecordServiceServer()
}

// UnimplementedRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordServiceServer struct{}

func (UnimplementedRecordServiceServer) DeleteWarning(context.Context, *DeleteWarningRecordRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWarning not implemented")
}
func (UnimplementedRecordServiceServer) DeleteWarningPlayback(context.Context, *DeleteWarningRecordRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWarningPlayback not implemented")
}
func (UnimplementedRecordServiceServer) DeleteWarningCapture(context.Context, *DeleteWarningRecordRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWarningCapture not implemented")
}
func (UnimplementedRecordServiceServer) mustEmbedUnimplementedRecordServiceServer() {}
func (UnimplementedRecordServiceServer) testEmbeddedByValue()                       {}

// UnsafeRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordServiceServer will
// result in compilation errors.
type UnsafeRecordServiceServer interface {
	mustEmbedUnimplementedRecordServiceServer()
}

func RegisterRecordServiceServer(s grpc.ServiceRegistrar, srv RecordServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordService_ServiceDesc, srv)
}

func _RecordService_DeleteWarning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarningRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteWarning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteWarning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteWarning(ctx, req.(*DeleteWarningRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteWarningPlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarningRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteWarningPlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteWarningPlayback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteWarningPlayback(ctx, req.(*DeleteWarningRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteWarningCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarningRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteWarningCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteWarningCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteWarningCapture(ctx, req.(*DeleteWarningRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordService_ServiceDesc is the grpc.ServiceDesc for RecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "record.RecordService",
	HandlerType: (*RecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteWarning",
			Handler:    _RecordService_DeleteWarning_Handler,
		},
		{
			MethodName: "DeleteWarningPlayback",
			Handler:    _RecordService_DeleteWarningPlayback_Handler,
		},
		{
			MethodName: "DeleteWarningCapture",
			Handler:    _RecordService_DeleteWarningCapture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "record/record.proto",
}
