// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: eap/eap.proto

package eap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_eap_eap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_eap_eap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_eap_eap_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SendTaskMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskMessageRequest) Reset() {
	*x = SendTaskMessageRequest{}
	mi := &file_eap_eap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskMessageRequest) ProtoMessage() {}

func (x *SendTaskMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eap_eap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskMessageRequest.ProtoReflect.Descriptor instead.
func (*SendTaskMessageRequest) Descriptor() ([]byte, []int) {
	return file_eap_eap_proto_rawDescGZIP(), []int{1}
}

func (x *SendTaskMessageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SendTaskMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendTaskMessageRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *SendTaskMessageRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type SendTaskMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskMessageResponse) Reset() {
	*x = SendTaskMessageResponse{}
	mi := &file_eap_eap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskMessageResponse) ProtoMessage() {}

func (x *SendTaskMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eap_eap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskMessageResponse.ProtoReflect.Descriptor instead.
func (*SendTaskMessageResponse) Descriptor() ([]byte, []int) {
	return file_eap_eap_proto_rawDescGZIP(), []int{2}
}

func (x *SendTaskMessageResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SendTaskMessageResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SendTaskMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_eap_eap_proto protoreflect.FileDescriptor

const file_eap_eap_proto_rawDesc = "" +
	"\n" +
	"\reap/eap.proto\x12\x03eap\"]\n" +
	"\n" +
	"Attachment\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\xa3\x01\n" +
	"\x16SendTaskMessageRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x121\n" +
	"\vattachments\x18\x04 \x03(\v2\x0f.eap.AttachmentR\vattachments\"h\n" +
	"\x17SendTaskMessageResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId2Y\n" +
	"\vTaskService\x12J\n" +
	"\vSendMessage\x12\x1b.eap.SendTaskMessageRequest\x1a\x1c.eap.SendTaskMessageResponse\"\x00B)Z'github.com/air-iot/api-client-go/v4/eapb\x06proto3"

var (
	file_eap_eap_proto_rawDescOnce sync.Once
	file_eap_eap_proto_rawDescData []byte
)

func file_eap_eap_proto_rawDescGZIP() []byte {
	file_eap_eap_proto_rawDescOnce.Do(func() {
		file_eap_eap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eap_eap_proto_rawDesc), len(file_eap_eap_proto_rawDesc)))
	})
	return file_eap_eap_proto_rawDescData
}

var file_eap_eap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eap_eap_proto_goTypes = []any{
	(*Attachment)(nil),              // 0: eap.Attachment
	(*SendTaskMessageRequest)(nil),  // 1: eap.SendTaskMessageRequest
	(*SendTaskMessageResponse)(nil), // 2: eap.SendTaskMessageResponse
}
var file_eap_eap_proto_depIdxs = []int32{
	0, // 0: eap.SendTaskMessageRequest.attachments:type_name -> eap.Attachment
	1, // 1: eap.TaskService.SendMessage:input_type -> eap.SendTaskMessageRequest
	2, // 2: eap.TaskService.SendMessage:output_type -> eap.SendTaskMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eap_eap_proto_init() }
func file_eap_eap_proto_init() {
	if File_eap_eap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eap_eap_proto_rawDesc), len(file_eap_eap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eap_eap_proto_goTypes,
		DependencyIndexes: file_eap_eap_proto_depIdxs,
		MessageInfos:      file_eap_eap_proto_msgTypes,
	}.Build()
	File_eap_eap_proto = out.File
	file_eap_eap_proto_goTypes = nil
	file_eap_eap_proto_depIdxs = nil
}
