// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.1
// source: syslog/syslog.proto

package syslog

import (
	context "context"
	api "github.com/air-iot/api-client-go/v4/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyslogServiceClient is the client API for SyslogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyslogServiceClient interface {
	Query(ctx context.Context, in *api.QueryRequest, opts ...grpc.CallOption) (*api.Response, error)
}

type syslogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyslogServiceClient(cc grpc.ClientConnInterface) SyslogServiceClient {
	return &syslogServiceClient{cc}
}

func (c *syslogServiceClient) Query(ctx context.Context, in *api.QueryRequest, opts ...grpc.CallOption) (*api.Response, error) {
	out := new(api.Response)
	err := c.cc.Invoke(ctx, "/syslog.SyslogService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyslogServiceServer is the server API for SyslogService service.
// All implementations must embed UnimplementedSyslogServiceServer
// for forward compatibility
type SyslogServiceServer interface {
	Query(context.Context, *api.QueryRequest) (*api.Response, error)
	mustEmbedUnimplementedSyslogServiceServer()
}

// UnimplementedSyslogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyslogServiceServer struct {
}

func (UnimplementedSyslogServiceServer) Query(context.Context, *api.QueryRequest) (*api.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSyslogServiceServer) mustEmbedUnimplementedSyslogServiceServer() {}

// UnsafeSyslogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyslogServiceServer will
// result in compilation errors.
type UnsafeSyslogServiceServer interface {
	mustEmbedUnimplementedSyslogServiceServer()
}

func RegisterSyslogServiceServer(s grpc.ServiceRegistrar, srv SyslogServiceServer) {
	s.RegisterService(&SyslogService_ServiceDesc, srv)
}

func _SyslogService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyslogServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syslog.SyslogService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyslogServiceServer).Query(ctx, req.(*api.QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyslogService_ServiceDesc is the grpc.ServiceDesc for SyslogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyslogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syslog.SyslogService",
	HandlerType: (*SyslogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _SyslogService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syslog/syslog.proto",
}
